language: cpp

os:
  - linux
  - osx

dist: focal

osx_image:
  - xcode12

compiler:
  - gcc
  # - clang

addons:
  apt:
    packages:
      - libboost-all-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update      ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install make; fi

  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost make; fi

script:
  - ./configure
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gmake --disable-shared             ; else make             ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gmake test --disable-shared        ; else make test        ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo gmake --disable-shared install; else sudo make install; fi

jobs:
  allow_failures:
    - os: osx

