language: cpp

os:
  - linux
  - osx

dist: focal

osx_image:
  - xcode12

compiler:
  - gcc
  # - clang

addons:
  apt:
    packages:
      - libboost-all-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update      ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install make; fi

  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost make; fi

script:
  - ./configure
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gmake NO_REVISION=1             ; else make NO_REVISION=1             ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gmake test NO_REVISION=1        ; else make test NO_REVISION=1        ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo gmake NO_REVISION=1 install; else sudo make install NO_REVISION=1; fi

jobs:
  allow_failures:
    - os: osx

